modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="recipes_for_create"
version="1.1.1"
displayName="Crafting Recipes For Create"
displayURL="https://github.com/BrayDo2010/Crafting-Recipes-For-Create"
credits="BrayDog2010, Jimmy2389438"
authors="BrayDog2010, Jimmy2389438"
description="This Mod Allows You To Craft Chipped With Creat"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.recipes_for_create]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.recipes_for_create]]
modId="minecraft"
mandatory=true
versionRange="[1.19.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.recipes_for_create]]
modId="create"
mandatory=true
versionRange="[0.5.0e,)"
ordering="NONE"
side="BOTH"

[[dependencies.recipes_for_create]]
modId="chipped"
mandatory=true
versionRange="[2.1.0,)"
ordering="NONE"
side="BOTH"

