modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="recipes_for_create"
version="0.7.0"
displayName="Crafting Recipes For Create"
displayURL="https://github.com/BrayDo2010/Crafting-Recipes-For-Create"
credits="Jimmy2389438, BrayDog2010"
authors="Jimmy2389438"
description="This Mod Allows You To Craft Chipped With Creat"

[[dependencies.recipes_for_create]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




